### ISSUE TITLE
Erro Fatal Windows

### ISSUE THREAD

**Issue by flod1** [PavlikPolivka/gitcleaner#1]
I have many local old branches on Intlly 2017.2.5 (Windows 10). But this plugin doesnt delete old branches. :-(
error 
git4idea.branch.GitBranchUiHandlerImpl.<init>(Lcom/intellij/openapi/project/Project;Lgit4idea/GitPlatformFacade;Lgit4idea/commands/Git;Lcom/intellij/openapi/progress/ProgressIndicator;)V
java.lang.NoSuchMethodError: git4idea.branch.GitBranchUiHandlerImpl.<init>(Lcom/intellij/openapi/project/Project;Lgit4idea/GitPlatformFacade;Lgit4idea/commands/Git;Lcom/intellij/openapi/progress/ProgressIndicator;)V
	at com.ppolivka.plugin.gitcleaner.BranchCleanerWorker.branchWorker(BranchCleanerWorker.java:94)
	at com.ppolivka.plugin.gitcleaner.BranchCleanerWorker.access$000(BranchCleanerWorker.java:23)
	at com.ppolivka.plugin.gitcleaner.BranchCleanerWorker$1.run(BranchCleanerWorker.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by PavlikPolivka** [comment]
Yeah I know, I tested everything on older version of IntelliJ and it worked there. It does not work with newer versions, working on fix.

**Comment by PavlikPolivka** [comment]
Jetbrains depreceted and deleted one API call in 2017 versions of IDEs. Unfortunately I developed and tested this on 2016. 
I fixed it submitted this release to repository, should be in few days, waiting for Jetbrains approval.
