### ISSUE TITLE
Gives an exception on the new intellij version

### ISSUE THREAD

**Issue by Bbbrinks** [PavlikPolivka/gitcleaner#6]
Shows the following exception when trying to open de Delete old branches dialog.

Intellij version: 2018.3 (IU-183.5153.38)

```
java.lang.IllegalStateException: The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 228,4,Idea Thread Group]
	at com.intellij.openapi.ui.DialogWrapper.ensureEventDispatchThread(DialogWrapper.java:2152)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1260)
	at com.intellij.openapi.ui.messages.MessageDialog._init(MessageDialog.java:99)
	at com.intellij.openapi.ui.messages.MessageDialog.<init>(MessageDialog.java:56)
	at com.intellij.ui.messages.MessagesServiceImpl.showMessageDialog(MessagesServiceImpl.java:69)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:209)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:169)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:777)
	at com.ppolivka.plugin.gitcleaner.BranchCleanerWorker.lambda$create$2(BranchCleanerWorker.java:108)
	at com.ppolivka.plugin.gitcleaner.WorkerUtil$1.run(WorkerUtil.java:28)
```

**Comment by trailsnail** [comment]
Here something similar:

in PhpStorm 2019.1.3
Build #PS-191.7479.51
JRE: 1.8.0_202-release-1483-b53 amd64

```
java.lang.IllegalStateException: The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 5,4,Idea Thread Group]
	at com.intellij.openapi.ui.DialogWrapper.ensureEventDispatchThread(DialogWrapper.java:2155)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1235)
	at com.intellij.openapi.ui.messages.MessageDialog._init(MessageDialog.java:99)
	at com.intellij.openapi.ui.messages.MessageDialog.<init>(MessageDialog.java:56)
	at com.intellij.ui.messages.MessagesServiceImpl.showMessageDialog(MessagesServiceImpl.java:69)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:218)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:177)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:790)
	at com.ppolivka.plugin.gitcleaner.BranchCleanerWorker.lambda$create$2(BranchCleanerWorker.java:108)
	at com.ppolivka.plugin.gitcleaner.WorkerUtil$1.run(WorkerUtil.java:28)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by carlosrafaelfernandes** [comment]
Yup same here
IntelliJ IDEA 2019.3.2 (Ultimate Edition)
Build #IU-193.6015.39, built on January 21, 2020
Runtime version: 11.0.5+10-b520.30 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

```
Following exceptions happened soon after this one, most probably they are induced.


2020-07-24T12:00:51.388
Access is allowed from event dispatch thread only.
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@6c9e5505
Current thread: Thread[Loading branch info...,4,Idea Thread Group] 205470700
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1789915911
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:959)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:948)
	at com.intellij.openapi.application.impl.LaterInvocator.getCurrentModalityState(LaterInvocator.java:325)
	at com.intellij.openapi.application.impl.LaterInvocator.enterModal(LaterInvocator.java:186)
	at com.intellij.ui.messages.SheetMessage.<init>(SheetMessage.java:135)
	at com.intellij.ui.messages.JBMacMessages.showMessageDialog(JBMacMessages.java:73)
	at com.intellij.ui.messages.MessagesServiceImpl.showMessageDialog(MessagesServiceImpl.java:59)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:222)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:181)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:819)
	at com.ppolivka.plugin.gitcleaner.BranchCleanerWorker.lambda$create$2(BranchCleanerWorker.java:108)
	at com.ppolivka.plugin.gitcleaner.WorkerUtil$1.run(WorkerUtil.java:28)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$4(ApplicationImpl.java:441)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:209)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)


2020-07-24T12:00:51.392
java.lang.IllegalStateException: The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[Loading branch info...,4,Idea Thread Group]
	at com.intellij.openapi.ui.DialogWrapper.ensureEventDispatchThread(DialogWrapper.java:2125)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1256)
	at com.intellij.openapi.ui.messages.MessageDialog._init(MessageDialog.java:99)
	at com.intellij.openapi.ui.messages.MessageDialog.<init>(MessageDialog.java:56)
	at com.intellij.ui.messages.MessagesServiceImpl.showMessageDialog(MessagesServiceImpl.java:68)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:222)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:181)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:819)
	at com.ppolivka.plugin.gitcleaner.BranchCleanerWorker.lambda$create$2(BranchCleanerWorker.java:108)
	at com.ppolivka.plugin.gitcleaner.WorkerUtil$1.run(WorkerUtil.java:28)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$4(ApplicationImpl.java:441)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:209)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sambernet** [comment]
Also happens on current `2022.1.2 (Ultimate)` version, build `#IU-221.5787.30`

I do see only the first exception from @carlosrafaelfernandes in the stack-trace, though (not the original one from @Bbbrinks or @trailsnail:

```
Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[ApplicationImpl pooled thread 409,4,main] 248320246
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1947225551
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1103)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1086)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:166)
	at com.intellij.openapi.wm.impl.WindowWatcher.getFocusedWindowForProject(WindowWatcher.java:307)
	at com.intellij.openapi.wm.impl.WindowWatcher.suggestParentWindow(WindowWatcher.java:220)
	at com.intellij.openapi.wm.impl.WindowManagerImpl.suggestParentWindow(WindowManagerImpl.kt:223)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.<init>(DialogWrapperPeerImpl.java:90)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerFactoryImpl.createPeer(DialogWrapperPeerFactoryImpl.java:25)
	at com.jetbrains.rdserver.ui.dialogs.BackendDialogWrapperPeerFactory.createPeer(BackendDialogWrapperPeerFactory.kt:51)
	at com.intellij.openapi.ui.DialogWrapper.createPeer(DialogWrapper.java:857)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:232)
	at com.intellij.ui.messages.AlertDialog.<init>(AlertMessagesManager.kt:98)
	at com.intellij.ui.messages.AlertMessagesManager.showMessageDialog(AlertMessagesManager.kt:63)
	at com.intellij.ui.messages.MessagesServiceImpl.showMessageDialog(MessagesServiceImpl.java:49)
	at com.jetbrains.rdserver.ui.BackendMessagesService.showMessageDialog(BackendMessagesService.kt:29)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:201)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:162)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:598)
	at com.ppolivka.plugin.gitcleaner.BranchCleanerWorker.lambda$create$2(BranchCleanerWorker.java:108)
	at com.ppolivka.plugin.gitcleaner.WorkerUtil$1.run(WorkerUtil.java:28)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:526)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:83)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Essentially this means the plugin is unusable on any reasonably current version.
